version: '3.8'  # You can adjust the version based on your Docker version compatibility

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"  # Corrected syntax for port mapping
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
